plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
repository: hi-wm/hi

{% for project_title in site.github.project_title %}
  * [William Harrison - FED @ Horizontal Integration]({{ repository.html_url }})
{% endfor %}